### ISSUE TITLE
Add BlackBox terminal

### ISSUE THREAD

**Issue by mambucodev** [Dvlv/BoxBuddyRS#143]
- [x] I have read the FAQs (https://dvlv.github.io/BoxBuddyRS/faqs)
- [x] My feature is not on the Roadmap (https://dvlv.github.io/BoxBuddyRS/ROADMAP)
- [x] I have searched for previous issues (https://github.com/Dvlv/BoxBuddyRS/issues?q=is%3Aissue+is%3Aclosed)

## Describe your feature request below
Could you add Black Box to terminals?

**Comment by Dvlv** [comment]
Hello,
Thanks for the suggestion, but it doesn't look like Blackbox is compatible with the way BoxBuddy spawns terminals

```
blackbox-terminal -c distrobox enter Arch
```

This command appears to be how you spawn it with a command, but it doesn't work for me in my fedora VM.

**Comment by mambucodev** [comment]
> Hello, Thanks for the suggestion, but it doesn't look like Blackbox is compatible with the way BoxBuddy spawns terminals
> 
> ```
> blackbox-terminal -c distrobox enter Arch
> ```
> 
> This command appears to be how you spawn it with a command, but it doesn't work for me in my fedora VM.

I think you missed something
```
blackbox-terminal -c "distrobox enter Arch"
```

**Comment by mambucodev** [comment]
Btw why close the issue so fast? I don't think that's very helpful for development in general.

**Comment by Dvlv** [comment]
> I think you missed something

No, Blackbox expects the command as a single argument, as you demonstrated, but BoxBuddy provides each argument separately. Thus, Blackbox is incompatible with BoxBuddy.

I haven't checked, but you can probably work around this using a wrapper script as documented [here in the FAQs.](https://www.dvlv.co.uk/BoxBuddyRS/faqs#my-preferred-terminal-is-a-flatpak-why-cant-boxbuddy-open-it) I believe you would just have to wrap the `$@` in quotes, and name the script after a terminal which you do not have installed, then set that as your Preferred Terminal. I know this is not ideal.

> Btw why close the issue so fast? I don't think that's very helpful for development in general.

I like to follow an Inbox Zero method of working, so if I see a (1) next to the Issues tab, this implies I have 1 thing to actively work on. As I have investigated this and concluded that I have nothing to work on, I have closed the issue to get rid of the (1).

I do not lock the issues, so people can continue commenting on them, and further disucssion leads to me having something to actively work on, I will then re-open the issue until that work is done.

Since this is a personal hobby project I maintain in my spare time, I manage it the way I find easiest to maintain.

(It would be nice for me if GitHub Issues had a third status, something like On Hold, where it would get rid of the (1) notification but not lose the issue amongst all of the others that I have finished working on. Since it does not, this is the best way I can think of to manage issues.)
