### ISSUE TITLE
Move build system to Meson

### ISSUE THREAD

**Issue by tfuxu** [Dvlv/BoxBuddyRS#98]
- [x] I have read the FAQs (https://dvlv.github.io/BoxBuddyRS/faqs)
- [x] My feature is not on the Roadmap (https://dvlv.github.io/BoxBuddyRS/ROADMAP)
- [x] I have searched for previous issues (https://github.com/Dvlv/BoxBuddyRS/issues?q=is%3Aissue+is%3Aclosed)

## Describe your feature request below
Many modern Gtk applications use Meson to manage compilation and packaging processes, as it is a _de facto_ build system of core GNOME apps. 

Move to Meson would allow to remove some boilerplate code for retrieving packaged icons (like [this](https://github.com/Dvlv/BoxBuddyRS/blob/master/src/utils.rs#L588-L614)), make code more readable and maintainable by (easily) moving UI definitions from Rust to [Blueprint](https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/) and create a standard environment for future contributors.

I've already made a minimal Meson configuration for BoxBuddy, and it works great for devel builds. I just need a green light from @Dvlv, to know if this is something that would be accepted into BoxBuddy codebase.

**Comment by Dvlv** [comment]
Hello
https://github.com/Dvlv/BoxBuddyRS/tree/meson-restructure
There's already a meson brach, I just never merged it into master as I couldn't see any particular benefit to moving the buildsystem.

> make code more readable and maintainable by (easily) moving UI definitions from Rust to [Blueprint](https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/)

I've never really "vibed with" this way of doing GTK (which is surprising since I work in web where the HTML is separate from the logic) I find it much easier to have everything together.

As well as this, I consider BoxBuddy essentially feature-complete, so I'm not sure it's worth the effort of rebuilding it all.
